/**
 * This class is generated by jOOQ
 */
package database.tables;


import database.Keys;
import database.Public;
import database.tables.records.CargoRecord;

import java.math.BigDecimal;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Cargo extends TableImpl<CargoRecord> {

    private static final long serialVersionUID = 295535496;

    /**
     * The reference instance of <code>public.cargo</code>
     */
    public static final Cargo CARGO = new Cargo();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CargoRecord> getRecordType() {
        return CargoRecord.class;
    }

    /**
     * The column <code>public.cargo.idcargo</code>.
     */
    public final TableField<CargoRecord, Integer> IDCARGO = createField("idcargo", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.cargo.nombre_cargo</code>.
     */
    public final TableField<CargoRecord, String> NOMBRE_CARGO = createField("nombre_cargo", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.cargo.sueldo</code>.
     */
    public final TableField<CargoRecord, BigDecimal> SUELDO = createField("sueldo", org.jooq.impl.SQLDataType.NUMERIC.precision(6, 2), this, "");

    /**
     * The column <code>public.cargo.aplica_mod</code>.
     */
    public final TableField<CargoRecord, Boolean> APLICA_MOD = createField("aplica_mod", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * Create a <code>public.cargo</code> table reference
     */
    public Cargo() {
        this("cargo", null);
    }

    /**
     * Create an aliased <code>public.cargo</code> table reference
     */
    public Cargo(String alias) {
        this(alias, CARGO);
    }

    private Cargo(String alias, Table<CargoRecord> aliased) {
        this(alias, aliased, null);
    }

    private Cargo(String alias, Table<CargoRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<CargoRecord> getPrimaryKey() {
        return Keys.CARGO_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<CargoRecord>> getKeys() {
        return Arrays.<UniqueKey<CargoRecord>>asList(Keys.CARGO_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Cargo as(String alias) {
        return new Cargo(alias, this);
    }

    /**
     * Rename this table
     */
    public Cargo rename(String name) {
        return new Cargo(name, null);
    }
}
