/**
 * This class is generated by jOOQ
 */
package database.tables;


import database.Keys;
import database.Public;
import database.tables.records.ClienteRecord;

import java.math.BigDecimal;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Cliente extends TableImpl<ClienteRecord> {

    private static final long serialVersionUID = -1839833372;

    /**
     * The reference instance of <code>public.cliente</code>
     */
    public static final Cliente CLIENTE = new Cliente();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ClienteRecord> getRecordType() {
        return ClienteRecord.class;
    }

    /**
     * The column <code>public.cliente.idcliente</code>.
     */
    public final TableField<ClienteRecord, Integer> IDCLIENTE = createField("idcliente", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.cliente.nombre</code>.
     */
    public final TableField<ClienteRecord, String> NOMBRE = createField("nombre", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.cliente.direccion</code>.
     */
    public final TableField<ClienteRecord, String> DIRECCION = createField("direccion", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.cliente.telefono</code>.
     */
    public final TableField<ClienteRecord, String> TELEFONO = createField("telefono", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.cliente.email</code>.
     */
    public final TableField<ClienteRecord, String> EMAIL = createField("email", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.cliente.nit</code>.
     */
    public final TableField<ClienteRecord, String> NIT = createField("nit", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.cliente.nrc</code>.
     */
    public final TableField<ClienteRecord, String> NRC = createField("nrc", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.cliente.representante_legal</code>.
     */
    public final TableField<ClienteRecord, String> REPRESENTANTE_LEGAL = createField("representante_legal", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.cliente.tipo_cliente</code>.
     */
    public final TableField<ClienteRecord, String> TIPO_CLIENTE = createField("tipo_cliente", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.cliente.tipo_transaccion</code>.
     */
    public final TableField<ClienteRecord, String> TIPO_TRANSACCION = createField("tipo_transaccion", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.cliente.limite_credito</code>.
     */
    public final TableField<ClienteRecord, BigDecimal> LIMITE_CREDITO = createField("limite_credito", org.jooq.impl.SQLDataType.NUMERIC.precision(6, 2), this, "");

    /**
     * The column <code>public.cliente.tiempo_pago</code>.
     */
    public final TableField<ClienteRecord, Integer> TIEMPO_PAGO = createField("tiempo_pago", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * Create a <code>public.cliente</code> table reference
     */
    public Cliente() {
        this("cliente", null);
    }

    /**
     * Create an aliased <code>public.cliente</code> table reference
     */
    public Cliente(String alias) {
        this(alias, CLIENTE);
    }

    private Cliente(String alias, Table<ClienteRecord> aliased) {
        this(alias, aliased, null);
    }

    private Cliente(String alias, Table<ClienteRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ClienteRecord> getPrimaryKey() {
        return Keys.CLIENTE_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ClienteRecord>> getKeys() {
        return Arrays.<UniqueKey<ClienteRecord>>asList(Keys.CLIENTE_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Cliente as(String alias) {
        return new Cliente(alias, this);
    }

    /**
     * Rename this table
     */
    public Cliente rename(String name) {
        return new Cliente(name, null);
    }
}
