/**
 * This class is generated by jOOQ
 */
package database.tables;


import database.Keys;
import database.Public;
import database.tables.records.CostoRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Costo extends TableImpl<CostoRecord> {

    private static final long serialVersionUID = -791313493;

    /**
     * The reference instance of <code>public.costo</code>
     */
    public static final Costo COSTO = new Costo();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CostoRecord> getRecordType() {
        return CostoRecord.class;
    }

    /**
     * The column <code>public.costo.idcosto</code>.
     */
    public final TableField<CostoRecord, Integer> IDCOSTO = createField("idcosto", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.costo.rubro</code>.
     */
    public final TableField<CostoRecord, String> RUBRO = createField("rubro", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.costo.valor_costo</code>.
     */
    public final TableField<CostoRecord, Integer> VALOR_COSTO = createField("valor_costo", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * Create a <code>public.costo</code> table reference
     */
    public Costo() {
        this("costo", null);
    }

    /**
     * Create an aliased <code>public.costo</code> table reference
     */
    public Costo(String alias) {
        this(alias, COSTO);
    }

    private Costo(String alias, Table<CostoRecord> aliased) {
        this(alias, aliased, null);
    }

    private Costo(String alias, Table<CostoRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<CostoRecord> getPrimaryKey() {
        return Keys.COSTO_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<CostoRecord>> getKeys() {
        return Arrays.<UniqueKey<CostoRecord>>asList(Keys.COSTO_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Costo as(String alias) {
        return new Costo(alias, this);
    }

    /**
     * Rename this table
     */
    public Costo rename(String name) {
        return new Costo(name, null);
    }
}
