/**
 * This class is generated by jOOQ
 */
package database.tables;


import database.Public;
import database.tables.records.DetalleformulaRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Detalleformula extends TableImpl<DetalleformulaRecord> {

    private static final long serialVersionUID = -1995406911;

    /**
     * The reference instance of <code>public.detalleformula</code>
     */
    public static final Detalleformula DETALLEFORMULA = new Detalleformula();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DetalleformulaRecord> getRecordType() {
        return DetalleformulaRecord.class;
    }

    /**
     * The column <code>public.detalleformula.idformula</code>.
     */
    public final TableField<DetalleformulaRecord, Integer> IDFORMULA = createField("idformula", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.detalleformula.idinsumo</code>.
     */
    public final TableField<DetalleformulaRecord, Integer> IDINSUMO = createField("idinsumo", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.detalleformula.cantidad</code>.
     */
    public final TableField<DetalleformulaRecord, Double> CANTIDAD = createField("cantidad", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>public.detalleformula.unidad_medida</code>.
     */
    public final TableField<DetalleformulaRecord, Integer> UNIDAD_MEDIDA = createField("unidad_medida", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * Create a <code>public.detalleformula</code> table reference
     */
    public Detalleformula() {
        this("detalleformula", null);
    }

    /**
     * Create an aliased <code>public.detalleformula</code> table reference
     */
    public Detalleformula(String alias) {
        this(alias, DETALLEFORMULA);
    }

    private Detalleformula(String alias, Table<DetalleformulaRecord> aliased) {
        this(alias, aliased, null);
    }

    private Detalleformula(String alias, Table<DetalleformulaRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Detalleformula as(String alias) {
        return new Detalleformula(alias, this);
    }

    /**
     * Rename this table
     */
    public Detalleformula rename(String name) {
        return new Detalleformula(name, null);
    }
}
