/**
 * This class is generated by jOOQ
 */
package database.tables;


import database.Keys;
import database.Public;
import database.tables.records.InsumosRecord;

import java.math.BigDecimal;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Insumos extends TableImpl<InsumosRecord> {

    private static final long serialVersionUID = -104178986;

    /**
     * The reference instance of <code>public.insumos</code>
     */
    public static final Insumos INSUMOS = new Insumos();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<InsumosRecord> getRecordType() {
        return InsumosRecord.class;
    }

    /**
     * The column <code>public.insumos.idinsumo</code>.
     */
    public final TableField<InsumosRecord, Integer> IDINSUMO = createField("idinsumo", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.insumos.nombre</code>.
     */
    public final TableField<InsumosRecord, String> NOMBRE = createField("nombre", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.insumos.idcategoria</code>.
     */
    public final TableField<InsumosRecord, Integer> IDCATEGORIA = createField("idcategoria", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.insumos.unidad_medida</code>.
     */
    public final TableField<InsumosRecord, String> UNIDAD_MEDIDA = createField("unidad_medida", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.insumos.costo</code>.
     */
    public final TableField<InsumosRecord, BigDecimal> COSTO = createField("costo", org.jooq.impl.SQLDataType.NUMERIC.precision(6, 2), this, "");

    /**
     * The column <code>public.insumos.max</code>.
     */
    public final TableField<InsumosRecord, Double> MAX = createField("max", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>public.insumos.min</code>.
     */
    public final TableField<InsumosRecord, Double> MIN = createField("min", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>public.insumos.stock</code>.
     */
    public final TableField<InsumosRecord, Double> STOCK = createField("stock", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * Create a <code>public.insumos</code> table reference
     */
    public Insumos() {
        this("insumos", null);
    }

    /**
     * Create an aliased <code>public.insumos</code> table reference
     */
    public Insumos(String alias) {
        this(alias, INSUMOS);
    }

    private Insumos(String alias, Table<InsumosRecord> aliased) {
        this(alias, aliased, null);
    }

    private Insumos(String alias, Table<InsumosRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<InsumosRecord> getPrimaryKey() {
        return Keys.INSUMOS_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<InsumosRecord>> getKeys() {
        return Arrays.<UniqueKey<InsumosRecord>>asList(Keys.INSUMOS_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Insumos as(String alias) {
        return new Insumos(alias, this);
    }

    /**
     * Rename this table
     */
    public Insumos rename(String name) {
        return new Insumos(name, null);
    }
}
