/**
 * This class is generated by jOOQ
 */
package database.tables;


import database.Keys;
import database.Public;
import database.tables.records.PedidoRecord;

import java.sql.Date;
import java.sql.Time;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Pedido extends TableImpl<PedidoRecord> {

    private static final long serialVersionUID = 756939779;

    /**
     * The reference instance of <code>public.pedido</code>
     */
    public static final Pedido PEDIDO = new Pedido();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PedidoRecord> getRecordType() {
        return PedidoRecord.class;
    }

    /**
     * The column <code>public.pedido.idpedido</code>.
     */
    public final TableField<PedidoRecord, Integer> IDPEDIDO = createField("idpedido", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.pedido.num_lote</code>.
     */
    public final TableField<PedidoRecord, Integer> NUM_LOTE = createField("num_lote", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.pedido.fecha</code>.
     */
    public final TableField<PedidoRecord, Date> FECHA = createField("fecha", org.jooq.impl.SQLDataType.DATE, this, "");

    /**
     * The column <code>public.pedido.cantidad</code>.
     */
    public final TableField<PedidoRecord, Double> CANTIDAD = createField("cantidad", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>public.pedido.idproducto</code>.
     */
    public final TableField<PedidoRecord, Integer> IDPRODUCTO = createField("idproducto", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.pedido.tiempo</code>.
     */
    public final TableField<PedidoRecord, Time> TIEMPO = createField("tiempo", org.jooq.impl.SQLDataType.TIME, this, "");

    /**
     * The column <code>public.pedido.estado</code>.
     */
    public final TableField<PedidoRecord, String> ESTADO = createField("estado", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * Create a <code>public.pedido</code> table reference
     */
    public Pedido() {
        this("pedido", null);
    }

    /**
     * Create an aliased <code>public.pedido</code> table reference
     */
    public Pedido(String alias) {
        this(alias, PEDIDO);
    }

    private Pedido(String alias, Table<PedidoRecord> aliased) {
        this(alias, aliased, null);
    }

    private Pedido(String alias, Table<PedidoRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<PedidoRecord> getPrimaryKey() {
        return Keys.PEDIDO_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<PedidoRecord>> getKeys() {
        return Arrays.<UniqueKey<PedidoRecord>>asList(Keys.PEDIDO_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Pedido as(String alias) {
        return new Pedido(alias, this);
    }

    /**
     * Rename this table
     */
    public Pedido rename(String name) {
        return new Pedido(name, null);
    }
}
