/**
 * This class is generated by jOOQ
 */
package database.tables;


import database.Keys;
import database.Public;
import database.tables.records.VentasRecord;

import java.math.BigDecimal;
import java.sql.Date;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Ventas extends TableImpl<VentasRecord> {

    private static final long serialVersionUID = -406349755;

    /**
     * The reference instance of <code>public.ventas</code>
     */
    public static final Ventas VENTAS = new Ventas();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VentasRecord> getRecordType() {
        return VentasRecord.class;
    }

    /**
     * The column <code>public.ventas.idventa</code>.
     */
    public final TableField<VentasRecord, Integer> IDVENTA = createField("idventa", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.ventas.num_documento</code>.
     */
    public final TableField<VentasRecord, Integer> NUM_DOCUMENTO = createField("num_documento", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.ventas.tipo_documento</code>.
     */
    public final TableField<VentasRecord, String> TIPO_DOCUMENTO = createField("tipo_documento", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.ventas.fecha</code>.
     */
    public final TableField<VentasRecord, Date> FECHA = createField("fecha", org.jooq.impl.SQLDataType.DATE, this, "");

    /**
     * The column <code>public.ventas.idcliente</code>.
     */
    public final TableField<VentasRecord, String> IDCLIENTE = createField("idcliente", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.ventas.abonos</code>.
     */
    public final TableField<VentasRecord, BigDecimal> ABONOS = createField("abonos", org.jooq.impl.SQLDataType.NUMERIC.precision(6, 2), this, "");

    /**
     * The column <code>public.ventas.tipo_venta</code>.
     */
    public final TableField<VentasRecord, String> TIPO_VENTA = createField("tipo_venta", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * Create a <code>public.ventas</code> table reference
     */
    public Ventas() {
        this("ventas", null);
    }

    /**
     * Create an aliased <code>public.ventas</code> table reference
     */
    public Ventas(String alias) {
        this(alias, VENTAS);
    }

    private Ventas(String alias, Table<VentasRecord> aliased) {
        this(alias, aliased, null);
    }

    private Ventas(String alias, Table<VentasRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<VentasRecord> getPrimaryKey() {
        return Keys.VENTAS_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<VentasRecord>> getKeys() {
        return Arrays.<UniqueKey<VentasRecord>>asList(Keys.VENTAS_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Ventas as(String alias) {
        return new Ventas(alias, this);
    }

    /**
     * Rename this table
     */
    public Ventas rename(String name) {
        return new Ventas(name, null);
    }
}
