/**
 * This class is generated by jOOQ
 */
package database.tables.records;


import database.tables.Cliente;

import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ClienteRecord extends UpdatableRecordImpl<ClienteRecord> implements Record12<Integer, String, String, String, String, String, String, String, String, String, BigDecimal, Integer> {

    private static final long serialVersionUID = 1353590209;

    /**
     * Setter for <code>public.cliente.idcliente</code>.
     */
    public void setIdcliente(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.cliente.idcliente</code>.
     */
    public Integer getIdcliente() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.cliente.nombre</code>.
     */
    public void setNombre(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.cliente.nombre</code>.
     */
    public String getNombre() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.cliente.direccion</code>.
     */
    public void setDireccion(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.cliente.direccion</code>.
     */
    public String getDireccion() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.cliente.telefono</code>.
     */
    public void setTelefono(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.cliente.telefono</code>.
     */
    public String getTelefono() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.cliente.email</code>.
     */
    public void setEmail(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.cliente.email</code>.
     */
    public String getEmail() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.cliente.nit</code>.
     */
    public void setNit(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.cliente.nit</code>.
     */
    public String getNit() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.cliente.nrc</code>.
     */
    public void setNrc(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.cliente.nrc</code>.
     */
    public String getNrc() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.cliente.representante_legal</code>.
     */
    public void setRepresentanteLegal(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.cliente.representante_legal</code>.
     */
    public String getRepresentanteLegal() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.cliente.tipo_cliente</code>.
     */
    public void setTipoCliente(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.cliente.tipo_cliente</code>.
     */
    public String getTipoCliente() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.cliente.tipo_transaccion</code>.
     */
    public void setTipoTransaccion(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.cliente.tipo_transaccion</code>.
     */
    public String getTipoTransaccion() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.cliente.limite_credito</code>.
     */
    public void setLimiteCredito(BigDecimal value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.cliente.limite_credito</code>.
     */
    public BigDecimal getLimiteCredito() {
        return (BigDecimal) get(10);
    }

    /**
     * Setter for <code>public.cliente.tiempo_pago</code>.
     */
    public void setTiempoPago(Integer value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.cliente.tiempo_pago</code>.
     */
    public Integer getTiempoPago() {
        return (Integer) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<Integer, String, String, String, String, String, String, String, String, String, BigDecimal, Integer> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<Integer, String, String, String, String, String, String, String, String, String, BigDecimal, Integer> valuesRow() {
        return (Row12) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Cliente.CLIENTE.IDCLIENTE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Cliente.CLIENTE.NOMBRE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Cliente.CLIENTE.DIRECCION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Cliente.CLIENTE.TELEFONO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Cliente.CLIENTE.EMAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Cliente.CLIENTE.NIT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Cliente.CLIENTE.NRC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Cliente.CLIENTE.REPRESENTANTE_LEGAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return Cliente.CLIENTE.TIPO_CLIENTE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return Cliente.CLIENTE.TIPO_TRANSACCION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field11() {
        return Cliente.CLIENTE.LIMITE_CREDITO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field12() {
        return Cliente.CLIENTE.TIEMPO_PAGO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getIdcliente();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getNombre();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getDireccion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getTelefono();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getNit();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getNrc();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getRepresentanteLegal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getTipoCliente();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getTipoTransaccion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value11() {
        return getLimiteCredito();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value12() {
        return getTiempoPago();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClienteRecord value1(Integer value) {
        setIdcliente(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClienteRecord value2(String value) {
        setNombre(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClienteRecord value3(String value) {
        setDireccion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClienteRecord value4(String value) {
        setTelefono(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClienteRecord value5(String value) {
        setEmail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClienteRecord value6(String value) {
        setNit(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClienteRecord value7(String value) {
        setNrc(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClienteRecord value8(String value) {
        setRepresentanteLegal(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClienteRecord value9(String value) {
        setTipoCliente(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClienteRecord value10(String value) {
        setTipoTransaccion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClienteRecord value11(BigDecimal value) {
        setLimiteCredito(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClienteRecord value12(Integer value) {
        setTiempoPago(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClienteRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9, String value10, BigDecimal value11, Integer value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ClienteRecord
     */
    public ClienteRecord() {
        super(Cliente.CLIENTE);
    }

    /**
     * Create a detached, initialised ClienteRecord
     */
    public ClienteRecord(Integer idcliente, String nombre, String direccion, String telefono, String email, String nit, String nrc, String representanteLegal, String tipoCliente, String tipoTransaccion, BigDecimal limiteCredito, Integer tiempoPago) {
        super(Cliente.CLIENTE);

        set(0, idcliente);
        set(1, nombre);
        set(2, direccion);
        set(3, telefono);
        set(4, email);
        set(5, nit);
        set(6, nrc);
        set(7, representanteLegal);
        set(8, tipoCliente);
        set(9, tipoTransaccion);
        set(10, limiteCredito);
        set(11, tiempoPago);
    }
}
