/**
 * This class is generated by jOOQ
 */
package database.tables.records;


import database.tables.Detallecompra;

import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DetallecompraRecord extends TableRecordImpl<DetallecompraRecord> implements Record4<Integer, Integer, Double, BigDecimal> {

    private static final long serialVersionUID = -1581770339;

    /**
     * Setter for <code>public.detallecompra.idcompra</code>.
     */
    public void setIdcompra(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.detallecompra.idcompra</code>.
     */
    public Integer getIdcompra() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.detallecompra.idinsumo</code>.
     */
    public void setIdinsumo(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.detallecompra.idinsumo</code>.
     */
    public Integer getIdinsumo() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.detallecompra.cantidad</code>.
     */
    public void setCantidad(Double value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.detallecompra.cantidad</code>.
     */
    public Double getCantidad() {
        return (Double) get(2);
    }

    /**
     * Setter for <code>public.detallecompra.precio</code>.
     */
    public void setPrecio(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.detallecompra.precio</code>.
     */
    public BigDecimal getPrecio() {
        return (BigDecimal) get(3);
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, Double, BigDecimal> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, Double, BigDecimal> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Detallecompra.DETALLECOMPRA.IDCOMPRA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Detallecompra.DETALLECOMPRA.IDINSUMO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field3() {
        return Detallecompra.DETALLECOMPRA.CANTIDAD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field4() {
        return Detallecompra.DETALLECOMPRA.PRECIO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getIdcompra();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getIdinsumo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value3() {
        return getCantidad();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value4() {
        return getPrecio();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DetallecompraRecord value1(Integer value) {
        setIdcompra(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DetallecompraRecord value2(Integer value) {
        setIdinsumo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DetallecompraRecord value3(Double value) {
        setCantidad(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DetallecompraRecord value4(BigDecimal value) {
        setPrecio(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DetallecompraRecord values(Integer value1, Integer value2, Double value3, BigDecimal value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DetallecompraRecord
     */
    public DetallecompraRecord() {
        super(Detallecompra.DETALLECOMPRA);
    }

    /**
     * Create a detached, initialised DetallecompraRecord
     */
    public DetallecompraRecord(Integer idcompra, Integer idinsumo, Double cantidad, BigDecimal precio) {
        super(Detallecompra.DETALLECOMPRA);

        set(0, idcompra);
        set(1, idinsumo);
        set(2, cantidad);
        set(3, precio);
    }
}
