/**
 * This class is generated by jOOQ
 */
package database.tables.records;


import database.tables.Detalleventa;

import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DetalleventaRecord extends TableRecordImpl<DetalleventaRecord> implements Record4<Integer, Double, Integer, BigDecimal> {

    private static final long serialVersionUID = -889219008;

    /**
     * Setter for <code>public.detalleventa.idventa</code>.
     */
    public void setIdventa(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.detalleventa.idventa</code>.
     */
    public Integer getIdventa() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.detalleventa.cantidad</code>.
     */
    public void setCantidad(Double value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.detalleventa.cantidad</code>.
     */
    public Double getCantidad() {
        return (Double) get(1);
    }

    /**
     * Setter for <code>public.detalleventa.idproducto</code>.
     */
    public void setIdproducto(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.detalleventa.idproducto</code>.
     */
    public Integer getIdproducto() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.detalleventa.precio</code>.
     */
    public void setPrecio(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.detalleventa.precio</code>.
     */
    public BigDecimal getPrecio() {
        return (BigDecimal) get(3);
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Double, Integer, BigDecimal> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Double, Integer, BigDecimal> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Detalleventa.DETALLEVENTA.IDVENTA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field2() {
        return Detalleventa.DETALLEVENTA.CANTIDAD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Detalleventa.DETALLEVENTA.IDPRODUCTO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field4() {
        return Detalleventa.DETALLEVENTA.PRECIO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getIdventa();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value2() {
        return getCantidad();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getIdproducto();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value4() {
        return getPrecio();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DetalleventaRecord value1(Integer value) {
        setIdventa(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DetalleventaRecord value2(Double value) {
        setCantidad(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DetalleventaRecord value3(Integer value) {
        setIdproducto(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DetalleventaRecord value4(BigDecimal value) {
        setPrecio(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DetalleventaRecord values(Integer value1, Double value2, Integer value3, BigDecimal value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DetalleventaRecord
     */
    public DetalleventaRecord() {
        super(Detalleventa.DETALLEVENTA);
    }

    /**
     * Create a detached, initialised DetalleventaRecord
     */
    public DetalleventaRecord(Integer idventa, Double cantidad, Integer idproducto, BigDecimal precio) {
        super(Detalleventa.DETALLEVENTA);

        set(0, idventa);
        set(1, cantidad);
        set(2, idproducto);
        set(3, precio);
    }
}
