/**
 * This class is generated by jOOQ
 */
package database.tables.records;


import database.tables.Empleado;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EmpleadoRecord extends UpdatableRecordImpl<EmpleadoRecord> implements Record8<Integer, String, String, String, String, String, String, Integer> {

    private static final long serialVersionUID = 315772355;

    /**
     * Setter for <code>public.empleado.idempleado</code>.
     */
    public void setIdempleado(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.empleado.idempleado</code>.
     */
    public Integer getIdempleado() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.empleado.nombre</code>.
     */
    public void setNombre(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.empleado.nombre</code>.
     */
    public String getNombre() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.empleado.direccion</code>.
     */
    public void setDireccion(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.empleado.direccion</code>.
     */
    public String getDireccion() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.empleado.telefono</code>.
     */
    public void setTelefono(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.empleado.telefono</code>.
     */
    public String getTelefono() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.empleado.email</code>.
     */
    public void setEmail(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.empleado.email</code>.
     */
    public String getEmail() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.empleado.nit</code>.
     */
    public void setNit(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.empleado.nit</code>.
     */
    public String getNit() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.empleado.dui</code>.
     */
    public void setDui(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.empleado.dui</code>.
     */
    public String getDui() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.empleado.idcargo</code>.
     */
    public void setIdcargo(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.empleado.idcargo</code>.
     */
    public Integer getIdcargo() {
        return (Integer) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, String, String, String, String, String, String, Integer> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, String, String, String, String, String, String, Integer> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Empleado.EMPLEADO.IDEMPLEADO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Empleado.EMPLEADO.NOMBRE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Empleado.EMPLEADO.DIRECCION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Empleado.EMPLEADO.TELEFONO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Empleado.EMPLEADO.EMAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Empleado.EMPLEADO.NIT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Empleado.EMPLEADO.DUI;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return Empleado.EMPLEADO.IDCARGO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getIdempleado();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getNombre();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getDireccion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getTelefono();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getNit();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getDui();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getIdcargo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmpleadoRecord value1(Integer value) {
        setIdempleado(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmpleadoRecord value2(String value) {
        setNombre(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmpleadoRecord value3(String value) {
        setDireccion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmpleadoRecord value4(String value) {
        setTelefono(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmpleadoRecord value5(String value) {
        setEmail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmpleadoRecord value6(String value) {
        setNit(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmpleadoRecord value7(String value) {
        setDui(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmpleadoRecord value8(Integer value) {
        setIdcargo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmpleadoRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6, String value7, Integer value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EmpleadoRecord
     */
    public EmpleadoRecord() {
        super(Empleado.EMPLEADO);
    }

    /**
     * Create a detached, initialised EmpleadoRecord
     */
    public EmpleadoRecord(Integer idempleado, String nombre, String direccion, String telefono, String email, String nit, String dui, Integer idcargo) {
        super(Empleado.EMPLEADO);

        set(0, idempleado);
        set(1, nombre);
        set(2, direccion);
        set(3, telefono);
        set(4, email);
        set(5, nit);
        set(6, dui);
        set(7, idcargo);
    }
}
