/**
 * This class is generated by jOOQ
 */
package database.tables.records;


import database.tables.Formula;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FormulaRecord extends UpdatableRecordImpl<FormulaRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = -2119511108;

    /**
     * Setter for <code>public.formula.idformula</code>.
     */
    public void setIdformula(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.formula.idformula</code>.
     */
    public Integer getIdformula() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.formula.nomb_producto</code>.
     */
    public void setNombProducto(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.formula.nomb_producto</code>.
     */
    public String getNombProducto() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Formula.FORMULA.IDFORMULA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Formula.FORMULA.NOMB_PRODUCTO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getIdformula();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getNombProducto();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FormulaRecord value1(Integer value) {
        setIdformula(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FormulaRecord value2(String value) {
        setNombProducto(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FormulaRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FormulaRecord
     */
    public FormulaRecord() {
        super(Formula.FORMULA);
    }

    /**
     * Create a detached, initialised FormulaRecord
     */
    public FormulaRecord(Integer idformula, String nombProducto) {
        super(Formula.FORMULA);

        set(0, idformula);
        set(1, nombProducto);
    }
}
