/**
 * This class is generated by jOOQ
 */
package database.tables.records;


import database.tables.Pedido;

import java.sql.Date;
import java.sql.Time;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PedidoRecord extends UpdatableRecordImpl<PedidoRecord> implements Record7<Integer, Integer, Date, Double, Integer, Time, String> {

    private static final long serialVersionUID = -1724681719;

    /**
     * Setter for <code>public.pedido.idpedido</code>.
     */
    public void setIdpedido(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.pedido.idpedido</code>.
     */
    public Integer getIdpedido() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.pedido.num_lote</code>.
     */
    public void setNumLote(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.pedido.num_lote</code>.
     */
    public Integer getNumLote() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.pedido.fecha</code>.
     */
    public void setFecha(Date value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.pedido.fecha</code>.
     */
    public Date getFecha() {
        return (Date) get(2);
    }

    /**
     * Setter for <code>public.pedido.cantidad</code>.
     */
    public void setCantidad(Double value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.pedido.cantidad</code>.
     */
    public Double getCantidad() {
        return (Double) get(3);
    }

    /**
     * Setter for <code>public.pedido.idproducto</code>.
     */
    public void setIdproducto(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.pedido.idproducto</code>.
     */
    public Integer getIdproducto() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.pedido.tiempo</code>.
     */
    public void setTiempo(Time value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.pedido.tiempo</code>.
     */
    public Time getTiempo() {
        return (Time) get(5);
    }

    /**
     * Setter for <code>public.pedido.estado</code>.
     */
    public void setEstado(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.pedido.estado</code>.
     */
    public String getEstado() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, Integer, Date, Double, Integer, Time, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, Integer, Date, Double, Integer, Time, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Pedido.PEDIDO.IDPEDIDO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Pedido.PEDIDO.NUM_LOTE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field3() {
        return Pedido.PEDIDO.FECHA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field4() {
        return Pedido.PEDIDO.CANTIDAD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return Pedido.PEDIDO.IDPRODUCTO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Time> field6() {
        return Pedido.PEDIDO.TIEMPO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Pedido.PEDIDO.ESTADO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getIdpedido();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getNumLote();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value3() {
        return getFecha();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value4() {
        return getCantidad();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getIdproducto();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Time value6() {
        return getTiempo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getEstado();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PedidoRecord value1(Integer value) {
        setIdpedido(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PedidoRecord value2(Integer value) {
        setNumLote(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PedidoRecord value3(Date value) {
        setFecha(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PedidoRecord value4(Double value) {
        setCantidad(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PedidoRecord value5(Integer value) {
        setIdproducto(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PedidoRecord value6(Time value) {
        setTiempo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PedidoRecord value7(String value) {
        setEstado(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PedidoRecord values(Integer value1, Integer value2, Date value3, Double value4, Integer value5, Time value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PedidoRecord
     */
    public PedidoRecord() {
        super(Pedido.PEDIDO);
    }

    /**
     * Create a detached, initialised PedidoRecord
     */
    public PedidoRecord(Integer idpedido, Integer numLote, Date fecha, Double cantidad, Integer idproducto, Time tiempo, String estado) {
        super(Pedido.PEDIDO);

        set(0, idpedido);
        set(1, numLote);
        set(2, fecha);
        set(3, cantidad);
        set(4, idproducto);
        set(5, tiempo);
        set(6, estado);
    }
}
