/**
 * This class is generated by jOOQ
 */
package database.tables.records;


import database.tables.Proveedor;

import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProveedorRecord extends UpdatableRecordImpl<ProveedorRecord> implements Record10<Integer, String, String, String, String, String, String, String, BigDecimal, Integer> {

    private static final long serialVersionUID = -509227316;

    /**
     * Setter for <code>public.proveedor.idproveedor</code>.
     */
    public void setIdproveedor(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.proveedor.idproveedor</code>.
     */
    public Integer getIdproveedor() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.proveedor.nombre</code>.
     */
    public void setNombre(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.proveedor.nombre</code>.
     */
    public String getNombre() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.proveedor.direccion</code>.
     */
    public void setDireccion(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.proveedor.direccion</code>.
     */
    public String getDireccion() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.proveedor.telefono</code>.
     */
    public void setTelefono(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.proveedor.telefono</code>.
     */
    public String getTelefono() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.proveedor.nit</code>.
     */
    public void setNit(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.proveedor.nit</code>.
     */
    public String getNit() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.proveedor.nrc</code>.
     */
    public void setNrc(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.proveedor.nrc</code>.
     */
    public String getNrc() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.proveedor.representante_legal</code>.
     */
    public void setRepresentanteLegal(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.proveedor.representante_legal</code>.
     */
    public String getRepresentanteLegal() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.proveedor.tipo_proveedor</code>.
     */
    public void setTipoProveedor(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.proveedor.tipo_proveedor</code>.
     */
    public String getTipoProveedor() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.proveedor.limite_credito</code>.
     */
    public void setLimiteCredito(BigDecimal value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.proveedor.limite_credito</code>.
     */
    public BigDecimal getLimiteCredito() {
        return (BigDecimal) get(8);
    }

    /**
     * Setter for <code>public.proveedor.tiempo_pago</code>.
     */
    public void setTiempoPago(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.proveedor.tiempo_pago</code>.
     */
    public Integer getTiempoPago() {
        return (Integer) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, String, String, String, String, String, String, String, BigDecimal, Integer> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, String, String, String, String, String, String, String, BigDecimal, Integer> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Proveedor.PROVEEDOR.IDPROVEEDOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Proveedor.PROVEEDOR.NOMBRE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Proveedor.PROVEEDOR.DIRECCION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Proveedor.PROVEEDOR.TELEFONO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Proveedor.PROVEEDOR.NIT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Proveedor.PROVEEDOR.NRC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Proveedor.PROVEEDOR.REPRESENTANTE_LEGAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Proveedor.PROVEEDOR.TIPO_PROVEEDOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field9() {
        return Proveedor.PROVEEDOR.LIMITE_CREDITO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field10() {
        return Proveedor.PROVEEDOR.TIEMPO_PAGO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getIdproveedor();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getNombre();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getDireccion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getTelefono();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getNit();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getNrc();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getRepresentanteLegal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getTipoProveedor();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value9() {
        return getLimiteCredito();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value10() {
        return getTiempoPago();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProveedorRecord value1(Integer value) {
        setIdproveedor(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProveedorRecord value2(String value) {
        setNombre(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProveedorRecord value3(String value) {
        setDireccion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProveedorRecord value4(String value) {
        setTelefono(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProveedorRecord value5(String value) {
        setNit(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProveedorRecord value6(String value) {
        setNrc(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProveedorRecord value7(String value) {
        setRepresentanteLegal(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProveedorRecord value8(String value) {
        setTipoProveedor(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProveedorRecord value9(BigDecimal value) {
        setLimiteCredito(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProveedorRecord value10(Integer value) {
        setTiempoPago(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProveedorRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, BigDecimal value9, Integer value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProveedorRecord
     */
    public ProveedorRecord() {
        super(Proveedor.PROVEEDOR);
    }

    /**
     * Create a detached, initialised ProveedorRecord
     */
    public ProveedorRecord(Integer idproveedor, String nombre, String direccion, String telefono, String nit, String nrc, String representanteLegal, String tipoProveedor, BigDecimal limiteCredito, Integer tiempoPago) {
        super(Proveedor.PROVEEDOR);

        set(0, idproveedor);
        set(1, nombre);
        set(2, direccion);
        set(3, telefono);
        set(4, nit);
        set(5, nrc);
        set(6, representanteLegal);
        set(7, tipoProveedor);
        set(8, limiteCredito);
        set(9, tiempoPago);
    }
}
