/**
 * This class is generated by jOOQ
 */
package database.tables.records;


import database.tables.Usuario;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsuarioRecord extends UpdatableRecordImpl<UsuarioRecord> implements Record3<Integer, String, String> {

    private static final long serialVersionUID = 1357718110;

    /**
     * Setter for <code>public.usuario.idusuario</code>.
     */
    public void setIdusuario(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.usuario.idusuario</code>.
     */
    public Integer getIdusuario() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.usuario.usuario</code>.
     */
    public void setUsuario(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.usuario.usuario</code>.
     */
    public String getUsuario() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.usuario.contraseña</code>.
     */
    public void setContraseña(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.usuario.contraseña</code>.
     */
    public String getContraseña() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Usuario.USUARIO.IDUSUARIO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Usuario.USUARIO.USUARIO_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Usuario.USUARIO.CONTRASEÑA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getIdusuario();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getUsuario();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getContraseña();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsuarioRecord value1(Integer value) {
        setIdusuario(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsuarioRecord value2(String value) {
        setUsuario(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsuarioRecord value3(String value) {
        setContraseña(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsuarioRecord values(Integer value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UsuarioRecord
     */
    public UsuarioRecord() {
        super(Usuario.USUARIO);
    }

    /**
     * Create a detached, initialised UsuarioRecord
     */
    public UsuarioRecord(Integer idusuario, String usuario, String contraseña) {
        super(Usuario.USUARIO);

        set(0, idusuario);
        set(1, usuario);
        set(2, contraseña);
    }
}
