/**
 * This class is generated by jOOQ
 */
package database;


import database.tables.Cargo;
import database.tables.Cliente;
import database.tables.Compra;
import database.tables.Costo;
import database.tables.Detallecompra;
import database.tables.Detalleformula;
import database.tables.Detalleventa;
import database.tables.Empleado;
import database.tables.Formula;
import database.tables.Insumos;
import database.tables.Pedido;
import database.tables.Productos;
import database.tables.Proveedor;
import database.tables.Usuario;
import database.tables.Ventas;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = -883158202;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.cargo</code>.
     */
    public final Cargo CARGO = database.tables.Cargo.CARGO;

    /**
     * The table <code>public.cliente</code>.
     */
    public final Cliente CLIENTE = database.tables.Cliente.CLIENTE;

    /**
     * The table <code>public.compra</code>.
     */
    public final Compra COMPRA = database.tables.Compra.COMPRA;

    /**
     * The table <code>public.costo</code>.
     */
    public final Costo COSTO = database.tables.Costo.COSTO;

    /**
     * The table <code>public.detallecompra</code>.
     */
    public final Detallecompra DETALLECOMPRA = database.tables.Detallecompra.DETALLECOMPRA;

    /**
     * The table <code>public.detalleformula</code>.
     */
    public final Detalleformula DETALLEFORMULA = database.tables.Detalleformula.DETALLEFORMULA;

    /**
     * The table <code>public.detalleventa</code>.
     */
    public final Detalleventa DETALLEVENTA = database.tables.Detalleventa.DETALLEVENTA;

    /**
     * The table <code>public.empleado</code>.
     */
    public final Empleado EMPLEADO = database.tables.Empleado.EMPLEADO;

    /**
     * The table <code>public.formula</code>.
     */
    public final Formula FORMULA = database.tables.Formula.FORMULA;

    /**
     * The table <code>public.insumos</code>.
     */
    public final Insumos INSUMOS = database.tables.Insumos.INSUMOS;

    /**
     * The table <code>public.pedido</code>.
     */
    public final Pedido PEDIDO = database.tables.Pedido.PEDIDO;

    /**
     * The table <code>public.productos</code>.
     */
    public final Productos PRODUCTOS = database.tables.Productos.PRODUCTOS;

    /**
     * The table <code>public.proveedor</code>.
     */
    public final Proveedor PROVEEDOR = database.tables.Proveedor.PROVEEDOR;

    /**
     * The table <code>public.usuario</code>.
     */
    public final Usuario USUARIO = database.tables.Usuario.USUARIO;

    /**
     * The table <code>public.ventas</code>.
     */
    public final Ventas VENTAS = database.tables.Ventas.VENTAS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Cargo.CARGO,
            Cliente.CLIENTE,
            Compra.COMPRA,
            Costo.COSTO,
            Detallecompra.DETALLECOMPRA,
            Detalleformula.DETALLEFORMULA,
            Detalleventa.DETALLEVENTA,
            Empleado.EMPLEADO,
            Formula.FORMULA,
            Insumos.INSUMOS,
            Pedido.PEDIDO,
            Productos.PRODUCTOS,
            Proveedor.PROVEEDOR,
            Usuario.USUARIO,
            Ventas.VENTAS);
    }
}
