/**
 * This class is generated by jOOQ
 */
package database;


import database.tables.Cargo;
import database.tables.Cliente;
import database.tables.Compra;
import database.tables.Costo;
import database.tables.Detallecompra;
import database.tables.Detalleformula;
import database.tables.Detalleventa;
import database.tables.Empleado;
import database.tables.Formula;
import database.tables.Insumos;
import database.tables.Pedido;
import database.tables.Productos;
import database.tables.Proveedor;
import database.tables.Usuario;
import database.tables.Ventas;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.cargo</code>.
     */
    public static final Cargo CARGO = database.tables.Cargo.CARGO;

    /**
     * The table <code>public.cliente</code>.
     */
    public static final Cliente CLIENTE = database.tables.Cliente.CLIENTE;

    /**
     * The table <code>public.compra</code>.
     */
    public static final Compra COMPRA = database.tables.Compra.COMPRA;

    /**
     * The table <code>public.costo</code>.
     */
    public static final Costo COSTO = database.tables.Costo.COSTO;

    /**
     * The table <code>public.detallecompra</code>.
     */
    public static final Detallecompra DETALLECOMPRA = database.tables.Detallecompra.DETALLECOMPRA;

    /**
     * The table <code>public.detalleformula</code>.
     */
    public static final Detalleformula DETALLEFORMULA = database.tables.Detalleformula.DETALLEFORMULA;

    /**
     * The table <code>public.detalleventa</code>.
     */
    public static final Detalleventa DETALLEVENTA = database.tables.Detalleventa.DETALLEVENTA;

    /**
     * The table <code>public.empleado</code>.
     */
    public static final Empleado EMPLEADO = database.tables.Empleado.EMPLEADO;

    /**
     * The table <code>public.formula</code>.
     */
    public static final Formula FORMULA = database.tables.Formula.FORMULA;

    /**
     * The table <code>public.insumos</code>.
     */
    public static final Insumos INSUMOS = database.tables.Insumos.INSUMOS;

    /**
     * The table <code>public.pedido</code>.
     */
    public static final Pedido PEDIDO = database.tables.Pedido.PEDIDO;

    /**
     * The table <code>public.productos</code>.
     */
    public static final Productos PRODUCTOS = database.tables.Productos.PRODUCTOS;

    /**
     * The table <code>public.proveedor</code>.
     */
    public static final Proveedor PROVEEDOR = database.tables.Proveedor.PROVEEDOR;

    /**
     * The table <code>public.usuario</code>.
     */
    public static final Usuario USUARIO = database.tables.Usuario.USUARIO;

    /**
     * The table <code>public.ventas</code>.
     */
    public static final Ventas VENTAS = database.tables.Ventas.VENTAS;
}
